# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analista', models.CharField(max_length=50)),
                ('denuncia', models.CharField(max_length=50)),
                ('linkDenuncia', models.CharField(max_length=500)),
                ('ticketAxur', models.CharField(max_length=50)),
                ('numeroFacebook', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-analista', '-denuncia'],
            },
        ),
    ]
