# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_mobile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
