# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishing',
            name='status',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
