# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0002_midia_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
